# Generated by Django 3.1.5 on 2021-01-21 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=10)),
                ('payment_date', models.DateTimeField()),
                ('bankingDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bankingdetail')),
                ('payment_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_from', to=settings.AUTH_USER_MODEL)),
                ('payment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
