# Generated by Django 3.1.5 on 2021-01-14 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=30)),
                ('bankCode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='BankingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=13)),
                ('accountHolder', models.CharField(max_length=30)),
                ('accountType', models.CharField(max_length=20)),
                ('bankId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
