# Generated by Django 3.1.5 on 2021-01-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(max_length=30)),
                ('shipment_number', models.CharField(max_length=30)),
                ('shipment_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shipment_option', models.CharField(max_length=30)),
                ('shipment_from', models.CharField(max_length=50)),
                ('shipment_to', models.CharField(max_length=50)),
                ('shipment_start_date', models.DateTimeField()),
                ('shipment_end_date', models.DateTimeField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorder')),
            ],
        ),
    ]
