# Generated by Django 3.1.5 on 2021-01-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('P', 'Phone'), ('L', 'Laptop'), ('D', 'Desktop'), ('W', 'Watch')], max_length=30)),
                ('category_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(choices=[('APL', 'Apple'), ('SAM', 'Samsung'), ('HAU', 'Hauwei'), ('NOK', 'Nokia'), ('SON', 'Sony')], default='APL', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('SB', 'Sealed In Box'), ('EX', 'Excellent'), ('FA', 'Fair'), ('DA', 'Damaged')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_year', models.CharField(max_length=4)),
                ('product_model', models.CharField(max_length=40)),
                ('product_condition', models.CharField(choices=[('SB', 'Sealed In Box'), ('EX', 'Excellent'), ('FA', 'Fair'), ('DA', 'Damaged')], default='SB', max_length=2)),
                ('product_type', models.CharField(max_length=50)),
                ('product_expected_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
        ),
    ]
