# Generated by Django 3.1.5 on 2021-03-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_model_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='category',
        ),
    ]
